#!/bin/sh

birch sample --config config/simulate.json --input input/simulate.json --output output/simulate.json
birch draw --input output/simulate.json --output figs/simulate.pdf
birch data --input output/simulate.json --output input/filter.json
